### ISSUE TITLE
jsassist-open-dccon의 Google Analytics 사용

### ISSUE THREAD

**Issue by rishubil** [krynen/jsassist-custom-css#1]
jsassist-open-dccon에서 사용하는 Google Analytics 코드가 그대로 사용되고 있습니다.
아래 표시한 파일의 Google Analytics 코드를 변경 또는 제거해주세요.

https://github.com/krynen/jsassist-custom-css/blob/a1f550a9d8897852cfd1035353b5674acb3d286a/list.html#L381-L396

https://github.com/krynen/jsassist-custom-css/blob/a1f550a9d8897852cfd1035353b5674acb3d286a/chat.html#L17-L32

**Comment by krynen** [comment]
코드 전체를 읽어보지 않아서 이런 경우를 생각하지 못했었네요.
말씀주셔서 감사합니다. 코드는 삭제했습니다.
